
CREATE OR REPLACE TRIGGER T1 
BEFORE DELETE OR INSERT OR UPDATE ON CUSTOMER 

FOR EACH ROW
WHEN (NEW.ID>0)

DECLARE

SAL_DIFF NUMBER;

BEGIN

SAL_DIFF:= :NEN.SALARY-: OLD.SALARY;

DBMS_OUTPUT.PUT_LINE ('OLD SALARY='||:OLD.SALARY);
DBMS_OUTPUT.PUT_LINE ('NEW SALARY='||:NEW.SALARY);
DBMS_OUTPUT.PUT_LINE ('SALARY DIFFERENCE='||:SAL_DIFF);

END;
--SET SERVEROUTPUT ON;
--UPDATE CUSTOMER
-- SET SALARY= 10000
-- WHERE ID=123;
