CREATE OR REPLACE TRIGGER T1
BEFORE DELETE OR INSERT OR UPDATE ON CUSTOMERS
FOR EACH ROW
WHEN (NEW.ID > 0)
DECLARE
  SAL_DIF NUMBER;
BEGIN
      SAL_DIF := :NEW.SALARY - :OLD.SALARY;
      DBMS_OUTPUT.PUT_LINE('OLD SALARY: ' || :OLD.SALARY);
      DBMS_OUTPUT.PUT_LINE('NEW SALARY: ' || :NEW.SALARY);
      DBMS_OUTPUT.PUT_LINE('SALARY DIFFERENCE: ' || SAL_DIF);
END;
/

--SET SERVEROUTPUT ON;
--UPDATE CUSTOMER
-- SET SALARY= 10000
-- WHERE ID=123;
