CREATE OR REPLACE PROCEDURE P1 IS

CURSOR C1 IS

SELECET E_ID,E_NAME ,AGE, SALARY FROM EMPLOYEE;

C_ID NUMBER;

C_NAME VARCHAR(20);

C_AGE NUMBER;

C_SALARY NUMBER;

BEGIN

OPEN C1
LOOP
FETCH C1 INTO C_ID, C_NAME ,C_AGE, C_SALARY;
EXIT WHEN C1%NOTFOUND;

DBMS_OUTPUT.PUT_LINE ('EMPLOYEE ID='||C_ID);
DBMS OUTPUT.PUT LINE ('EMPLOYEE NAME='||C_NAME);
DBMS_OUTPUT.PUT_LINE ('AGE='||C_AGE);
DBMS_OUTPUT.PUT_LINE ('SALARY='||:C_SALARY);

END LOOP;
CLOSE C1;
END;
END;
/
--/
--set serveroutput on;
-- execute P1;
